server:
  port: 8087

spring:
  application:
    name: worker

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

application:
  queue:
    name: locations
    exchange: direct-exchange
    routing-key: routing-key