server:
  port: 8083

spring:
  application:
    name: courier
  datasource:
    username: 'sezer'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/courier

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 5

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

application:
  location-queue-config:
    name: locations
    exchange: direct-locations
    routing-key: routing-locations
  log-queue-config:
    name: logs
    exchange: direct-logs
    routing-key: routing-logs